### ISSUE TITLE
无法展示graphml

### ISSUE THREAD

**Issue by hbh112233abc** [Ikaros-521/GraphRAG-Ollama-UI#14]
报错信息如下
```shell
Traceback (most recent call last):
  File "/home/hbh/anaconda3/envs/graphrag-ollama/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/hbh/anaconda3/envs/graphrag-ollama/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/hbh/anaconda3/envs/graphrag-ollama/lib/python3.10/site-packages/gradio/blocks.py", line 1907, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/home/hbh/anaconda3/envs/graphrag-ollama/lib/python3.10/site-packages/gradio/blocks.py", line 1730, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/hbh/anaconda3/envs/graphrag-ollama/lib/python3.10/site-packages/gradio/components/plot.py", line 138, in postprocess
    elif "bokeh" in value.__module__:
AttributeError: 'tuple' object has no attribute '__module__'. Did you mean: '__mul__'?
```
是因为依赖版本不对么

gradio                    4.38.1
gradio_client             1.1.0

**Comment by hbh112233abc** [comment]
原来是`app.py`的`update_visualization`方法最终返回有问题,直接`return fig`就可以了

**Comment by Ikaros-521** [comment]
> update_visualization

最近官方也还在持续更新，后续准备直接做官方汉化和功能验证了。
他那更新的内容 有些感觉没有完全实现就推到主线了。

不过你这的问题，我倒是没有遇到过。感觉还是系统问题造成的 库内容有偏差

**Comment by Ikaros-521** [comment]
> > update_visualization
> 
> 最近官方也还在持续更新，后续准备直接做官方汉化和功能验证了。 他那更新的内容 有些感觉没有完全实现就推到主线了。
> 
> 不过你这的问题，我倒是没有遇到过。感觉还是系统问题造成的 库内容有偏差

好吧，可能测的时候版本卡中间， 我这边把这个bug提交了吧

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/GraphRAG-Ollama-UI/commit/bfeccbdcc8a294bdd1eb267965094eebbea6640e
