### ISSUE TITLE
python app.py运行之后显示报错

### ISSUE THREAD

**Issue by 26Ssr** [Ikaros-521/GraphRAG-Ollama-UI#17]
python app.py运行之后显示报错
Traceback (most recent call last):
  File "/home/dd/app.py", line 67, in <module>
    os.environ.setdefault("LLM_API_BASE", os.getenv("LLM_API_BASE"))
  File "/usr/lib/python3.10/os.py", line 717, in setdefault
    self[key] = value
  File "/usr/lib/python3.10/os.py", line 685, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.10/os.py", line 757, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

**Comment by Ikaros-521** [comment]
环境变量 .env 创建后，配置 LLM_API_BASE
