### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by wmcde** [Ikaros-521/GraphRAG-Ollama-UI#21]
Traceback (most recent call last):
File "/home/sysadmin/anaconda3/envs/graphrag-local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/sysadmin/anaconda3/envs/graphrag-local/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/__main__.py", line 76, in <module>
index_cli(
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/cli.py", line 161, in index_cli
_run_workflow_async()
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/cli.py", line 159, in _run_workflow_async
asyncio.run(execute())
File "/home/sysadmin/anaconda3/envs/graphrag-local/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/cli.py", line 123, in execute
async for output in run_pipeline_with_config(
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/run.py", line 144, in run_pipeline_with_config
dataset = dataset if dataset is not None else await _create_input(config.input)
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/run.py", line 133, in _create_input
return await load_input(config, progress_reporter, root_dir)
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/input/load_input.py", line 81, in load_input
results = await loader(config, progress, storage)
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/input/text.py", line 55, in load
return pd.DataFrame([await load_file(file, group) for file, group in files])
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/input/text.py", line 55, in <listcomp>
return pd.DataFrame([await load_file(file, group) for file, group in files])
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/input/text.py", line 37, in load_file
text = await storage.get(path, encoding="utf-8")
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/storage/file_pipeline_storage.py", line 86, in get
return await self._read_file(file_path, as_bytes, encoding)
File "/home/sysadmin/GraphRAG-Ollama-UI/graphrag/index/storage/file_pipeline_storage.py", line 109, in _read_file
return await f.read()
File "/home/sysadmin/anaconda3/envs/graphrag-local/lib/python3.10/site-packages/aiofiles/threadpool/utils.py", line 43, in method
return await self._loop.run_in_executor(self._executor, cb)
File "/home/sysadmin/anaconda3/envs/graphrag-local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/sysadmin/anaconda3/envs/graphrag-local/lib/python3.10/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by Ikaros-521** [comment]
You can manually edit files and save them to the build directory, but there is a bug in the file editing function provided by webui

**Comment by wmcde** [comment]
After manually importing the file into input, this error still persists. But using 
“python -m graphrag.index --root ./ragtest” directly can run normally. 
Where does the problem lie?

**Comment by Ikaros-521** [comment]
> After manually importing the file into input, this error still persists. But using “python -m graphrag.index --root ./ragtest” directly can run normally. Where does the problem lie?
```
python -m graphrag.index --root ./ragtest
```
The site-packages library's graphrag is used, while the webui uses locally backed up graphrag, and errors may occur within the local backup

**Comment by Ikaros-521** [comment]
such `, encoding="utf-8"`，you can try The codes that report errors in the global replacement source code  such as ISO-8859-1, UTF-16, or Windows-1252.
