### ISSUE TITLE
Error executing verb "cluster_graph" in create_base_entity_graph: EmptyNetworkError details=None

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/GraphRAG-Ollama-UI#4]
```
23:48:23,643 datashaper.workflow.workflow INFO executing verb cluster_graph
23:48:23,647 datashaper.workflow.workflow ERROR Error executing verb "cluster_graph" in create_base_entity_graph: EmptyNetworkError
Traceback (most recent call last):
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 61, in cluster_graph
    results = output_df[column].apply(lambda graph: run_layout(strategy, graph))
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\series.py", line 4924, in apply
    ).apply()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\apply.py", line 1427, in apply
    return self.apply_standard()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\apply.py", line 1507, in apply_standard
    mapped = obj._map_values(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 61, in <lambda>
    results = output_df[column].apply(lambda graph: run_layout(strategy, graph))
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 198, in run_layout
    clusters = run_leiden(graph, strategy)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\strategies\leiden.py", line 26, in run
    node_id_to_community_map = _compute_leiden_communities(
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\strategies\leiden.py", line 61, in _compute_leiden_communities
    community_mapping = hierarchical_leiden(
  File "<@beartype(graspologic.partition.leiden.hierarchical_leiden) at 0x1e42609b370>", line 304, in hierarchical_leiden
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\graspologic\partition\leiden.py", line 588, in hierarchical_leiden
    hierarchical_clusters_native = gn.hierarchical_leiden(
leiden.EmptyNetworkError: EmptyNetworkError
23:48:23,651 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "cluster_graph" in create_base_entity_graph: EmptyNetworkError details=None
23:48:23,651 graphrag.index.run ERROR error running workflow create_base_entity_graph
Traceback (most recent call last):
  File "F:\GraphRAG-Ollama-UI\graphrag\index\run.py", line 357, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 61, in cluster_graph
    results = output_df[column].apply(lambda graph: run_layout(strategy, graph))
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\series.py", line 4924, in apply
    ).apply()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\apply.py", line 1427, in apply
    return self.apply_standard()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\apply.py", line 1507, in apply_standard
    mapped = obj._map_values(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 61, in <lambda>
    results = output_df[column].apply(lambda graph: run_layout(strategy, graph))
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 198, in run_layout
    clusters = run_leiden(graph, strategy)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\strategies\leiden.py", line 26, in run
    node_id_to_community_map = _compute_leiden_communities(
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\strategies\leiden.py", line 61, in _compute_leiden_communities
    community_mapping = hierarchical_leiden(
  File "<@beartype(graspologic.partition.leiden.hierarchical_leiden) at 0x1e42609b370>", line 304, in hierarchical_leiden
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\graspologic\partition\leiden.py", line 588, in hierarchical_leiden
    hierarchical_clusters_native = gn.hierarchical_leiden(
leiden.EmptyNetworkError: EmptyNetworkError
23:48:23,652 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
```

**Comment by Ikaros-521** [comment]
跟踪参考：https://github.com/microsoft/graphrag/issues/562

**Comment by Ikaros-521** [comment]
llm换了 qwen2，不稳定
