### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2386: illegal multibyte sequence

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/GraphRAG-Ollama-UI#5]
```
Traceback (most recent call last):
File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "F:\GraphRAG-Ollama-UI\graphrag\index\__main__.py", line 76, in <module>
index_cli(
File "F:\GraphRAG-Ollama-UI\graphrag\index\cli.py", line 97, in index_cli
pipeline_config: str | PipelineConfig = config or _create_default_config(
File "F:\GraphRAG-Ollama-UI\graphrag\index\cli.py", line 243, in _create_default_config
result = create_pipeline_config(parameters, verbose)
File "F:\GraphRAG-Ollama-UI\graphrag\index\create_pipeline_config.py", line 132, in create_pipeline_config
*_graph_workflows(settings, embedded_fields),
File "F:\GraphRAG-Ollama-UI\graphrag\index\create_pipeline_config.py", line 291, in _graph_workflows
"strategy": settings.entity_extraction.resolved_strategy(
File "F:\GraphRAG-Ollama-UI\graphrag\config\models\entity_extraction_config.py", line 41, in resolved_strategy
"extraction_prompt": (Path(root_dir) / self.prompt).read_text()
File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\pathlib.py", line 1135, in read_text
return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2386: illegal multibyte sequence
```

**Comment by Ikaros-521** [comment]
![image](https://github.com/user-attachments/assets/8b3c7726-e13d-4a2b-91a2-48d9c9fb7079)
