### ISSUE TITLE
Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key details=None

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/GraphRAG-Ollama-UI#6]
```
16:51:24,972 datashaper.workflow.workflow INFO executing verb cluster_graph
16:51:24,972 graphrag.index.verbs.graph.clustering.cluster_graph WARNING Graph has no nodes
16:51:24,974 datashaper.workflow.workflow ERROR Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key
Traceback (most recent call last):
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 102, in cluster_graph
    output_df[[level_to, to]] = pd.DataFrame(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\indexers\utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
16:51:24,976 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key details=None
16:51:24,976 graphrag.index.run ERROR error running workflow create_base_entity_graph
Traceback (most recent call last):
  File "F:\GraphRAG-Ollama-UI\graphrag\index\run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 102, in cluster_graph
    output_df[[level_to, to]] = pd.DataFrame(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\pandas\core\indexers\utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
16:51:24,977 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None

```

**Comment by Ikaros-521** [comment]
https://github.com/microsoft/graphrag/issues/631
更换LLM为 gemma2 解决
