### ISSUE TITLE
HTTP Request: POST http://127.0.0.1:11434/v1/embeddings "HTTP/1.1 404 Not Found"

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/GraphRAG-Ollama-UI#8]
```
17:05:16,974 httpcore.http11 DEBUG receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Length', b'18'), (b'Connection', b'keep-alive'), (b'Content-Type', b'text/plain'), (b'Date', b'Mon, 22 Jul 2024 09:05:16 GMT'), (b'Keep-Alive', b'timeout=4'), (b'Proxy-Connection', b'keep-alive')])
17:05:16,974 httpx INFO HTTP Request: POST http://127.0.0.1:11434/v1/embeddings "HTTP/1.1 404 Not Found"
17:05:16,974 httpcore.http11 DEBUG receive_response_body.started request=<Request [b'POST']>
17:05:16,974 httpcore.http11 DEBUG receive_response_body.complete
17:05:16,974 httpcore.http11 DEBUG response_closed.started
17:05:16,974 httpcore.http11 DEBUG response_closed.complete
17:05:16,974 httpcore.connection DEBUG close.started
17:05:16,974 httpcore.connection DEBUG close.complete
17:05:16,974 openai._base_client DEBUG HTTP Request: POST http://127.0.0.1:11434/v1/embeddings "404 Not Found"
17:05:16,974 openai._base_client DEBUG Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\_base_client.py", line 1599, in _request
    response.raise_for_status()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\httpx\_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://127.0.0.1:11434/v1/embeddings'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
17:05:16,976 openai._base_client DEBUG Re-raising status error
17:05:16,976 graphrag.index.reporting.file_workflow_callbacks INFO Error Invoking LLM details={'input': ['"ALICE ARAUJO MARQUES DE S\xc1":"Alice is a researcher in the field of Design and Biomimicry, working at the University of Bras��lia, focusing on creating innovative projects that utilize biological knowledge. She conducts systematic reviews to identify, describe, and analyze contributions of biomimicry to design.") ("entity"', '"STANISLAV N. GORB":"Stanislav N. Gorb" is not only an Academic Editor but also a renowned researcher in the field of biomechanics with significant contributions to the understanding of animal locomotion, making him a key figure in Biomimetics 2023."', '"BIOMIMETICS SOCIETY":', '"SUPPORTING BODY":', '"CONTRIBUTOR":', '"INTERCONNECTIONS AND CREATIVE":"Interconnections and Creative is an unspecified organization."', '"COMPLETE"|>("ENTITY":']}
17:05:16,977 datashaper.workflow.workflow ERROR Error executing verb "text_embed" in create_final_entities: 404 page not found
Traceback (most recent call last):
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 62, in run
    embeddings = await _execute(llm, text_batches, ticker, semaphore)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 106, in _execute
    results = await asyncio.gather(*futures)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\asyncio\tasks.py", line 304, in __wakeup
    future.result()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 100, in embed
    chunk_embeddings = await llm(chunk)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\caching_llm.py", line 104, in __call__
    result = await self._delegate(input, **kwargs)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\tenacity\asyncio\__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\base_llm.py", line 49, in __call__
    return await self._invoke(input, **kwargs)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\base_llm.py", line 53, in _invoke
    output = await self._execute_llm(input, **kwargs)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\openai\openai_embeddings_llm.py", line 36, in _execute_llm
    embedding = await self.client.embeddings.create(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\resources\embeddings.py", line 215, in create
    return await self._post(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\_base_client.py", line 1826, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\_base_client.py", line 1519, in request
    return await self._request(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\_base_client.py", line 1620, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found
17:05:16,980 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "text_embed" in create_final_entities: 404 page not found details=None
17:05:16,980 graphrag.index.run ERROR error running workflow create_final_entities
Traceback (most recent call last):
  File "F:\GraphRAG-Ollama-UI\graphrag\index\run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 62, in run
    embeddings = await _execute(llm, text_batches, ticker, semaphore)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 106, in _execute
    results = await asyncio.gather(*futures)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\asyncio\tasks.py", line 304, in __wakeup
    future.result()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 100, in embed
    chunk_embeddings = await llm(chunk)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\caching_llm.py", line 104, in __call__
    result = await self._delegate(input, **kwargs)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\tenacity\asyncio\__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\base_llm.py", line 49, in __call__
    return await self._invoke(input, **kwargs)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\base\base_llm.py", line 53, in _invoke
    output = await self._execute_llm(input, **kwargs)
  File "F:\GraphRAG-Ollama-UI\graphrag\llm\openai\openai_embeddings_llm.py", line 36, in _execute_llm
    embedding = await self.client.embeddings.create(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\resources\embeddings.py", line 215, in create
    return await self._post(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\_base_client.py", line 1826, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\_base_client.py", line 1519, in request
    return await self._request(
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\openai\_base_client.py", line 1620, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found
17:05:16,981 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None

```

**Comment by Ikaros-521** [comment]
ollama embedding接口改
EMBEDDINGS_API_BASE=http://127.0.0.1:11434/api

```
embeddings:
  async_mode: threaded
  llm:
    api_base: http://127.0.0.1:11434/api
```
